# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-29 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_auto_20180625_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCover',
            fields=[
                ('insurance_cover_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('public_liability', models.NullBooleanField(default=None)),
                ('application_id', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.CASCADE, to='application.NannyApplication')),
            ],
            options={
                'db_table': 'INSURANCE_COVER',
            },
        ),
    ]
