# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-02 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_dbscheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='childcareaddress',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
