# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-02 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_merge_20180702_0909'),
        ('application', '0017_childcareaddress_date_created'),
    ]

    operations = [
    ]
