# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-06 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_merge_20180702_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('declaration_id', models.UUIDField(default=uuid.UUID('50c9cb56-654a-403e-b8e4-9dc8bc5d6588'), primary_key=True, serialize=False)),
                ('register_rules', models.NullBooleanField()),
                ('share_information', models.NullBooleanField()),
                ('information_correct', models.NullBooleanField()),
                ('notify_information_change', models.NullBooleanField()),
                ('application_id', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.CASCADE, to='application.NannyApplication')),
            ],
        ),
    ]
