# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-09 15:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_merge_20180702_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999)])),
            ],
            options={
                'db_table': 'APPLICATION_REFERENCE',
            },
        ),
    ]
