# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-06 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_declaration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='declaration_id',
            field=models.UUIDField(default=uuid.UUID('4b5e59b0-8071-4545-83ba-20700f2c8b19'), primary_key=True, serialize=False),
        ),
    ]
