# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-09 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0021_auto_20180706_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='declaration_id',
            field=models.UUIDField(default=uuid.UUID('4ee35bef-4708-42bb-82f7-da301d4d3126'), primary_key=True, serialize=False),
        ),
    ]
