# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-09 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0022_auto_20180709_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='declaration_id',
            field=models.UUIDField(default=uuid.UUID('5c977308-6978-49e6-8cc3-8abccdb8157b'), primary_key=True, serialize=False),
        ),
    ]
