# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-09 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0023_auto_20180709_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='declaration_id',
            field=models.UUIDField(default=uuid.UUID('9413d4c1-2f87-4766-8594-6ae5fd2817a4'), primary_key=True, serialize=False),
        ),
    ]
