# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-09 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0025_auto_20180709_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='declaration_id',
            field=models.UUIDField(default=uuid.UUID('e3185d02-bde1-4022-8be0-ba5d6ad67615'), primary_key=True, serialize=False),
        ),
    ]
