# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-10 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0027_auto_20180710_0828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nannyapplication',
            old_name='display_contact_details_on_web',
            new_name='follow_rules',
        ),
        migrations.RemoveField(
            model_name='nannyapplication',
            name='information_correct_declare',
        ),
        migrations.AlterField(
            model_name='declaration',
            name='declaration_id',
            field=models.UUIDField(default=uuid.UUID('2add8c95-8e3d-4dec-a7c3-fcb7d1bf63cd'), primary_key=True, serialize=False),
        ),
    ]
