# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-10 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0028_auto_20180710_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nannyapplication',
            name='references_status',
        ),
        migrations.AlterField(
            model_name='declaration',
            name='declaration_id',
            field=models.UUIDField(default=uuid.UUID('c6700972-c142-4fdb-a3d9-6bac26fb2dbd'), primary_key=True, serialize=False),
        ),
    ]
