# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-10 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0029_auto_20180710_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nannyapplication',
            old_name='suitable_declare',
            new_name='information_correct_declare',
        ),
        migrations.AlterField(
            model_name='declaration',
            name='declaration_id',
            field=models.UUIDField(default=uuid.UUID('9e2f863f-4515-4cc5-9356-aa35a8da09fa'), primary_key=True, serialize=False),
        ),
    ]
