# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-10 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0030_auto_20180710_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='declaration_id',
            field=models.UUIDField(default=uuid.UUID('d5a26b39-b711-4fca-b185-825f5513730e'), primary_key=True, serialize=False),
        ),
    ]
