# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-10 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0032_auto_20180710_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='declaration_id',
            field=models.UUIDField(default=uuid.UUID('8f121082-2a56-4192-8777-613a4f148b0e'), primary_key=True, serialize=False),
        ),
    ]
