# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-10 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0033_auto_20180710_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='declaration_id',
            field=models.UUIDField(default=uuid.UUID('1e0b8d23-1626-4ac6-a067-3788f17cb660'), primary_key=True, serialize=False),
        ),
    ]
