# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-10 07:43
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0036_auto_20180809_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='declaration_id',
            field=models.UUIDField(default=uuid.UUID('d583309f-e69b-4529-baea-7a0071b5b071'), primary_key=True, serialize=False),
        ),
    ]
