# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-11 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0036_auto_20180711_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicanthomeaddress',
            name='current_address',
        ),
        migrations.AlterField(
            model_name='declaration',
            name='declaration_id',
            field=models.UUIDField(default=uuid.UUID('03d030a4-3891-499f-ae9c-bce80316cc6f'), primary_key=True, serialize=False),
        ),
    ]
