# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-12 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0037_auto_20180711_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='declaration_id',
            field=models.UUIDField(default=uuid.UUID('4f1dd8ae-8f1d-4947-803d-4e7594642f22'), primary_key=True, serialize=False),
        ),
    ]
