# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-10 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0037_auto_20180810_0743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arccomments',
            name='table_name',
        ),
        migrations.AlterField(
            model_name='declaration',
            name='declaration_id',
            field=models.UUIDField(default=uuid.UUID('fb07bf68-538d-42dd-9b7a-f7be36a7e76e'), primary_key=True, serialize=False),
        ),
    ]
