# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-23 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0038_auto_20180712_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicanthomeaddress',
            name='current_address',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='declaration_id',
            field=models.UUIDField(default=uuid.UUID('a8c9ad51-ed7f-4b77-abeb-16962df335a9'), primary_key=True, serialize=False),
        ),
    ]
