# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-17 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0039_auto_20180815_0857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nannyapplication',
            old_name='criminal_record_check_status',
            new_name='dbs_status',
        ),
        migrations.RenameField(
            model_name='nannyapplication',
            old_name='first_aid_training_status',
            new_name='first_aid_status',
        ),
    ]
