# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-26 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0039_auto_20180723_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='declaration_id',
            field=models.UUIDField(default=uuid.UUID('e33bf70f-a6ce-4664-aa81-851a1e425414'), primary_key=True, serialize=False),
        ),
    ]
