# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-27 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0040_auto_20180726_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='declaration_id',
            field=models.UUIDField(default=uuid.UUID('ccb6da5b-65b8-4da8-a756-a034cc5a1cd1'), primary_key=True, serialize=False),
        ),
    ]
