# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-15 20:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('application', '0041_auto_20180817_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.TextField(blank=True, null=True, verbose_name='object id')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('extra_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='extra data')),
                ('user', models.TextField(blank=True, null=True)),
                ('template', models.CharField(default='timeline_logger/application_action.txt', max_length=200)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType', verbose_name='content type')),
            ],
            options={
                'verbose_name_plural': 'timeline log entries',
                'verbose_name': 'timeline log entry',
            },
        ),
    ]
