# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-08 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0041_auto_20180727_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='declaration_id',
            field=models.UUIDField(default=uuid.UUID('3012fd47-61c2-402f-9693-5d39c9167350'), primary_key=True, serialize=False),
        ),
    ]
