# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-08 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0041_auto_20180817_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='childcareaddress',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
