# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-15 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0042_applicantpersonaldetails_your_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='nannyapplication',
            name='your_children_arc_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nannyapplication',
            name='your_children_status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FLAGGED', 'FLAGGED')], default='NOT_STARTED', max_length=50),
        ),
    ]
