# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-08 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0042_auto_20180808_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='declaration_id',
            field=models.UUIDField(default=uuid.UUID('f4b49655-aac3-4b19-bbc1-7b31720fb388'), primary_key=True, serialize=False),
        ),
    ]
