# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-16 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0043_auto_20181015_1254'),
        ('application', '0042_timelinelog'),
    ]

    operations = [
    ]
