# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-08 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0043_auto_20180808_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='declaration_id',
            field=models.UUIDField(default=uuid.UUID('25a3047a-5a6e-469b-8555-96829072698b'), primary_key=True, serialize=False),
        ),
    ]
