# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-23 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0044_merge_20181016_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dbscheck',
            old_name='convictions',
            new_name='has_convictions',
        ),
        migrations.AddField(
            model_name='dbscheck',
            name='is_ofsted_dbs',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='dbscheck',
            name='lived_abroad',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='dbscheck',
            name='on_dbs_update_service',
            field=models.NullBooleanField(default=None),
        ),
    ]
