# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-09 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0044_auto_20180808_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='declaration_id',
            field=models.UUIDField(default=uuid.UUID('1df93549-e805-47e2-82f8-5b6f6f04d4d2'), primary_key=True, serialize=False),
        ),
    ]
