# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-24 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0045_applicantchildrendetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantchildrendetails',
            name='lives_with_applicant',
            field=models.NullBooleanField(),
        ),
    ]
