# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-23 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0045_auto_20181023_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbscheck',
            name='dbs_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
