# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-29 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0046_auto_20181023_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dbscheck',
            old_name='has_convictions',
            new_name='convictions',
        ),
    ]
