# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-31 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0047_auto_20181029_0933'),
        ('application', '0046_applicantchildrendetails_lives_with_applicant'),
    ]

    operations = [
    ]
