# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-01 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0048_merge_20181031_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbscheck',
            name='lived_abroad',
            field=models.NullBooleanField(default=None),
        ),
    ]
