# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-05 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0048_auto_20181101_1053'),
        ('application', '0049_auto_20181101_1140'),
    ]

    operations = [
    ]
