# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-06 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0050_merge_20181105_1008'),
        ('application', '0050_merge_20181105_1500'),
    ]

    operations = [
    ]
