# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-14 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0051_merge_20181106_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbscheck',
            name='certificate_information',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dbscheck',
            name='within_three_months',
            field=models.NullBooleanField(default=None),
        ),
    ]
