# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-14 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0052_auto_20190214_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbscheck',
            name='enhanced_check',
            field=models.NullBooleanField(default=None),
        ),
    ]
