# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-19 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0053_dbscheck_enhanced_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbscheck',
            name='certificate_information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
