# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-19 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0054_auto_20190219_1249'),
        ('application', '0052_auto_20190214_0959'),
    ]

    operations = [
    ]
