# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-22 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0055_merge_20190219_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantpersonaldetails',
            name='your_children',
        ),
        migrations.AddField(
            model_name='applicantpersonaldetails',
            name='known_to_social_services',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='applicantpersonaldetails',
            name='reasons_known_to_social_services',
            field=models.TextField(default='', null=True),
        ),
    ]
