# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-27 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0057_auto_20190225_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantpersonaldetails',
            name='lived_abroad',
        ),
    ]
