# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-28 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0057_auto_20190225_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='childcareaddress',
            name='home_address',
            field=models.NullBooleanField(),
        ),
    ]
