# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-01 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0058_remove_applicantpersonaldetails_lived_abroad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantpersonaldetails',
            name='post_certificate_declaration',
        ),
    ]
