# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-01 12:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0058_childcareaddress_home_address'),
        ('application', '0059_remove_applicantpersonaldetails_post_certificate_declaration'),
    ]

    operations = [
    ]
