# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-07 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0060_merge_20190301_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='NannyPreviousRegistrationDetails',
            fields=[
                ('previous_registration_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('previous_registration', models.BooleanField(default=False)),
                ('individual_id', models.IntegerField(blank=True, default=0, null=True)),
                ('five_years_in_UK', models.BooleanField(default=False)),
                ('application_id', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.CASCADE, to='application.NannyApplication')),
            ],
            options={
                'db_table': 'PREVIOUS_REGISTRATION_DETAILS',
            },
        ),
    ]
