# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-08 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0061_nannypreviousregistrationdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='nannypreviousregistrationdetails',
            name='personal_detail_id',
            field=models.ForeignKey(db_column='personal_detail_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='application.ApplicantPersonalDetails'),
        ),
        migrations.AlterField(
            model_name='nannypreviousregistrationdetails',
            name='five_years_in_UK',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='nannypreviousregistrationdetails',
            name='previous_registration',
            field=models.NullBooleanField(),
        ),
    ]
