# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-11 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0062_nannypreviousregistrationdetails'),
        ('application', '0061_auto_20190308_1051'),
    ]

    operations = [
    ]
