# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0065_remove_nannypreviousregistrationdetails_personal_detail_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='nannyapplication',
            name='application_expiry_email_sent',
            field=models.NullBooleanField(default=False),
        ),
    ]
