# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-19 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0065_remove_nannypreviousregistrationdetails_personal_detail_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousAddress',
            fields=[
                ('previous_address_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('person_id', models.UUIDField(blank=True)),
                ('person_type', models.CharField(blank=True, choices=[('APPLICANT', 'APPLICANT')], max_length=50)),
                ('street_line1', models.CharField(blank=True, max_length=100)),
                ('street_line2', models.CharField(blank=True, max_length=100)),
                ('town', models.CharField(blank=True, max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('postcode', models.CharField(blank=True, max_length=100)),
                ('moved_in_date', models.DateField(blank=True, null=True)),
                ('moved_out_date', models.DateField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PREVIOUS_ADDRESS',
            },
        ),
    ]
