# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-15 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0061_nannypreviousregistrationdetails'),
        ('application', '0065_remove_nannypreviousregistrationdetails_personal_detail_id'),
    ]

    operations = [
    ]
