# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-19 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0065_remove_nannypreviousregistrationdetails_personal_detail_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NannyPreviousName',
            fields=[
                ('previous_name_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('application_id', models.UUIDField(blank=True)),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('middle_names', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('start_day', models.IntegerField(blank=True, null=True)),
                ('start_month', models.IntegerField(blank=True, null=True)),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('end_day', models.IntegerField(blank=True, null=True)),
                ('end_month', models.IntegerField(blank=True, null=True)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PREVIOUS_NAME',
            },
        ),
    ]
