# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-20 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0066_nannypreviousname'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantpersonaldetails',
            name='name_end_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicantpersonaldetails',
            name='name_end_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicantpersonaldetails',
            name='name_end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicantpersonaldetails',
            name='name_start_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicantpersonaldetails',
            name='name_start_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicantpersonaldetails',
            name='name_start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
