# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-22 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0066_previousaddress'),
        ('application', '0067_auto_20190320_1713'),
    ]

    operations = [
    ]
