# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-22 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0067_auto_20190320_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='nannyapplication',
            name='date_last_accessed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
