# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-25 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0068_merge_20190322_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicanthomeaddress',
            name='move_in_month',
        ),
        migrations.RemoveField(
            model_name='applicanthomeaddress',
            name='move_in_year',
        ),
        migrations.AddField(
            model_name='applicantpersonaldetails',
            name='moved_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicantpersonaldetails',
            name='moved_out_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
