# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0069_auto_20190325_1253'),
        ('application', '0068_nannyapplication_date_last_accessed'),
    ]

    operations = [
    ]
