# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-27 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0066_nannyapplication_application_expiry_email_sent'),
        ('application', '0070_merge_20190326_1327'),
    ]

    operations = [
    ]
