# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-09 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0071_merge_20190327_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantpersonaldetails',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
