# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-21 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0072_applicantpersonaldetails_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantpersonaldetails',
            name='application_id',
            field=models.OneToOneField(db_column='application_id', on_delete=django.db.models.deletion.CASCADE, to='application.NannyApplication'),
        ),
    ]
